Study vocab API changes
VEuPathDB/EdaSubsettingService pull request #107
Opened 2023-07-28 17:15 UTC by dmgaldi

API Changes for study vocab endpoint.

2023-08-01 16:23 UTC, d-callan commented on schema/library.raml
> +      studyEntity: string
so is the idea that studyEntity will be the megastudy id?

2023-08-01 16:23 UTC, d-callan commented on src/main/java/org/veupathdb/service/eda/ss/service/StudiesService.java
> +  public PostStudiesEntitiesVariablesStudyVocabByStudyIdAndEntityIdAndVariableIdResponse postStudiesEntitiesVariablesStudyVocabByStudyIdAndEntityIdAndVariableId(String studyId, String entityId, Strin
lol thats a doozy of a name

2023-08-01 16:23 UTC, d-callan commented on schema/library.raml
> +      studyEntity: string
maybe we could make this more clear, if this endpoint is megastudy specific? or do we want it to not be megastudy specific, and call StudyVocab something else?

2023-08-01 17:45 UTC, dmgaldi commented on schema/library.raml
> +      studyEntity: string
Yeah, it techincally doesn't need to be megastudy specific. We could do this trick for any entity. I'm of two minds about it. I was thinking we _could_ validate it so that any variables passed in would need to be annotated with `hasStudySpecificVocab` or whatever that annotation is called. If we do that, we would want to keep the name study-specific. 

However, if we want to just allow this endpoint to be used more generally, there might not be any major downsides. It could just lead to using it without understanding it's original intention.

2023-08-01 17:46 UTC, dmgaldi commented on src/main/java/org/veupathdb/service/eda/ss/service/StudiesService.java
> +  public PostStudiesEntitiesVariablesStudyVocabByStudyIdAndEntityIdAndVariableIdResponse postStudiesEntitiesVariablesStudyVocabByStudyIdAndEntityIdAndVariableId(String studyId, String entityId, Strin
Haha yeah, this is just how raml names nested endpoints. It's so unreadable D:

2023-08-01 17:47 UTC, dmgaldi commented on schema/library.raml
> +      studyEntity: string
Agree that it could be more clear though. I'm not sure what to call a "sub-study" of a mega study but it should be the entity-type of that if we do go the mega-study specific approach.

2023-08-01 18:23 UTC, d-callan commented on schema/library.raml
> +      studyEntity: string
could always assume the root-most entity and name it following that?

2023-08-02 17:48 UTC, dmgaldi commented on schema/library.raml
> +      studyEntity: string
That sounds good, I talked to Ryan during scrum and he likes this idea too.

2023-08-03 16:07 UTC, ryanrdoherty requested changes

2023-08-03 16:07 UTC, ryanrdoherty commented on src/main/java/org/veupathdb/service/eda/ss/service/StudiesService.java
> +      Variable var = study.getEntity(entityId)
I think you should move all these validation steps creating and returning your (essentially) StreamingOutput.   If I remember right, once Jersey commits to handing over the OutputStream to the streaming response, it has already written 200 response code which can't be taken back.  The client will get a response body it doesn't expect with these exception messages.

2023-08-03 20:41 UTC, ryanrdoherty approved these changes

2023-08-07 16:20 UTC, merged